version: '3'
services:
  doccano:
    image: doccano/doccano
    container_name: medical-ner-doccano
    ports:
      - "8001:8000"
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: password
      ADMIN_EMAIL: admin@example.com
    volumes:
      - ../data:/data
      - ./exports:/exports
    restart: unless-stopped