services:
  doccano:
    image: doccano/doccano
    container_name: toxicity-bias-doccano
    ports:
      - "8002:8000"
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: password
      ADMIN_EMAIL: admin@example.com
    volumes:
      - ./data:/data
      - ./output:/exports
    restart: unless-stopped