name: offensive_lang
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - scikit-learn
  - pyyaml
  - numpy
  - jupyter
  - pip:
    # Core Label Studio with compatible versions
    - "label-studio==1.7.3"
    - "django==3.2.16"
    - "django-cors-headers==3.6.0"  # Exact version required by label-studio
    - "django-filter==2.4.0"
    - "djangorestframework==3.12.0"
    - "label-studio-sdk==0.0.23"
    
    # Additional useful packages
    - "requests>=2.25.0"
    - "python-dotenv>=0.19.0"
    - "openpyxl>=3.0.0"  # For Excel file handling
    
    # Data processing
    - "matplotlib>=3.5.0"
    - "seaborn>=0.11.0"